# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ivan.kishchenko/Projects/cpp/serial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ivan.kishchenko/Projects/cpp/serial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.15.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ivan.kishchenko/Projects/cpp/serial/CMakeFiles /Users/ivan.kishchenko/Projects/cpp/serial/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ivan.kishchenko/Projects/cpp/serial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named serial_example

# Build rule for target.
serial_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serial_example
.PHONY : serial_example

# fast build rule for target.
serial_example/fast:
	$(MAKE) -f CMakeFiles/serial_example.dir/build.make CMakeFiles/serial_example.dir/build
.PHONY : serial_example/fast

#=============================================================================
# Target rules for targets named serial

# Build rule for target.
serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serial
.PHONY : serial

# fast build rule for target.
serial/fast:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/build
.PHONY : serial/fast

examples/serial_example.o: examples/serial_example.cc.o

.PHONY : examples/serial_example.o

# target to build an object file
examples/serial_example.cc.o:
	$(MAKE) -f CMakeFiles/serial_example.dir/build.make CMakeFiles/serial_example.dir/examples/serial_example.cc.o
.PHONY : examples/serial_example.cc.o

examples/serial_example.i: examples/serial_example.cc.i

.PHONY : examples/serial_example.i

# target to preprocess a source file
examples/serial_example.cc.i:
	$(MAKE) -f CMakeFiles/serial_example.dir/build.make CMakeFiles/serial_example.dir/examples/serial_example.cc.i
.PHONY : examples/serial_example.cc.i

examples/serial_example.s: examples/serial_example.cc.s

.PHONY : examples/serial_example.s

# target to generate assembly for a file
examples/serial_example.cc.s:
	$(MAKE) -f CMakeFiles/serial_example.dir/build.make CMakeFiles/serial_example.dir/examples/serial_example.cc.s
.PHONY : examples/serial_example.cc.s

src/impl/list_ports/list_ports_osx.o: src/impl/list_ports/list_ports_osx.cc.o

.PHONY : src/impl/list_ports/list_ports_osx.o

# target to build an object file
src/impl/list_ports/list_ports_osx.cc.o:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/impl/list_ports/list_ports_osx.cc.o
.PHONY : src/impl/list_ports/list_ports_osx.cc.o

src/impl/list_ports/list_ports_osx.i: src/impl/list_ports/list_ports_osx.cc.i

.PHONY : src/impl/list_ports/list_ports_osx.i

# target to preprocess a source file
src/impl/list_ports/list_ports_osx.cc.i:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/impl/list_ports/list_ports_osx.cc.i
.PHONY : src/impl/list_ports/list_ports_osx.cc.i

src/impl/list_ports/list_ports_osx.s: src/impl/list_ports/list_ports_osx.cc.s

.PHONY : src/impl/list_ports/list_ports_osx.s

# target to generate assembly for a file
src/impl/list_ports/list_ports_osx.cc.s:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/impl/list_ports/list_ports_osx.cc.s
.PHONY : src/impl/list_ports/list_ports_osx.cc.s

src/impl/unix.o: src/impl/unix.cc.o

.PHONY : src/impl/unix.o

# target to build an object file
src/impl/unix.cc.o:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/impl/unix.cc.o
.PHONY : src/impl/unix.cc.o

src/impl/unix.i: src/impl/unix.cc.i

.PHONY : src/impl/unix.i

# target to preprocess a source file
src/impl/unix.cc.i:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/impl/unix.cc.i
.PHONY : src/impl/unix.cc.i

src/impl/unix.s: src/impl/unix.cc.s

.PHONY : src/impl/unix.s

# target to generate assembly for a file
src/impl/unix.cc.s:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/impl/unix.cc.s
.PHONY : src/impl/unix.cc.s

src/serial.o: src/serial.cc.o

.PHONY : src/serial.o

# target to build an object file
src/serial.cc.o:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/serial.cc.o
.PHONY : src/serial.cc.o

src/serial.i: src/serial.cc.i

.PHONY : src/serial.i

# target to preprocess a source file
src/serial.cc.i:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/serial.cc.i
.PHONY : src/serial.cc.i

src/serial.s: src/serial.cc.s

.PHONY : src/serial.s

# target to generate assembly for a file
src/serial.cc.s:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/src/serial.cc.s
.PHONY : src/serial.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... test"
	@echo "... serial_example"
	@echo "... list_install_components"
	@echo "... serial"
	@echo "... examples/serial_example.o"
	@echo "... examples/serial_example.i"
	@echo "... examples/serial_example.s"
	@echo "... src/impl/list_ports/list_ports_osx.o"
	@echo "... src/impl/list_ports/list_ports_osx.i"
	@echo "... src/impl/list_ports/list_ports_osx.s"
	@echo "... src/impl/unix.o"
	@echo "... src/impl/unix.i"
	@echo "... src/impl/unix.s"
	@echo "... src/serial.o"
	@echo "... src/serial.i"
	@echo "... src/serial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

